FROM amio/node-chrome
WORKDIR /ltzcore

# Add source
COPY lerna.json ./
COPY package*.json ./

COPY  ./packages/ltzcore-client/package.json ./packages/ltzcore-client/package.json
COPY  ./packages/ltzcore-build/package.json ./packages/ltzcore-build/package.json
COPY  ./packages/ltzcore-lib/package.json ./packages/ltzcore-lib/package.json
COPY  ./packages/ltzcore-mnemonic/package.json ./packages/ltzcore-mnemonic/package.json
COPY  ./packages/ltzcore-node/package.json ./packages/ltzcore-node/package.json
COPY  ./packages/ltzcore-p2p/package.json ./packages/ltzcore-p2p/package.json
COPY  ./packages/ltzcore-wallet-client/package.json ./packages/ltzcore-wallet-client/package.json
COPY  ./packages/ltzcore-wallet-service/package.json ./packages/ltzcore-wallet-service/package.json
COPY  ./packages/ltzcore-payment-protocol/package.json ./packages/ltzcore-payment-protocol/package.json
COPY  ./packages/ltzcore-wallet/package.json ./packages/ltzcore-wallet/package.json
COPY  ./packages/insight-previous/package.json ./packages/insight-previous/package.json
COPY  ./packages/insight/package.json ./packages/insight/package.json

RUN npm install
RUN npm run bootstrap
ADD . .
RUN npm run compile
